ALTER TABLE spells ADD COLUMN is_cleric_spell   INTEGER NOT NULL DEFAULT 0;
ALTER TABLE spells ADD COLUMN is_druid_spell    INTEGER NOT NULL DEFAULT 0;
ALTER TABLE spells ADD COLUMN is_bard_spell     INTEGER NOT NULL DEFAULT 0;
ALTER TABLE spells ADD COLUMN is_paladin_spell  INTEGER NOT NULL DEFAULT 0;
ALTER TABLE spells ADD COLUMN is_ranger_spell   INTEGER NOT NULL DEFAULT 0;
ALTER TABLE spells ADD COLUMN is_sorcerer_spell INTEGER NOT NULL DEFAULT 0;
ALTER TABLE spells ADD COLUMN is_warlock_spell  INTEGER NOT NULL DEFAULT 0;

-- ─── Cleric ───────────────────────────────────────────────────────────────────
UPDATE spells SET is_cleric_spell = 1 WHERE id IN (
  'spell_guidance','spell_light','spell_mending','spell_resistance','spell_sacred_flame',
  'spell_spare_the_dying','spell_thaumaturgy','spell_toll_the_dead','spell_word_of_radiance',
  'spell_bane','spell_bless','spell_command','spell_create_or_destroy_water','spell_cure_wounds',
  'spell_detect_evil_and_good','spell_detect_magic','spell_detect_poison_and_disease',
  'spell_guiding_bolt','spell_healing_word','spell_inflict_wounds',
  'spell_protection_from_evil_and_good','spell_purify_food_and_drink','spell_sanctuary',
  'spell_shield_of_faith',
  'spell_aid','spell_augury','spell_blindness_deafness','spell_calm_emotions',
  'spell_continual_flame','spell_enhance_ability','spell_find_traps','spell_gentle_repose',
  'spell_hold_person','spell_lesser_restoration','spell_locate_object','spell_prayer_of_healing',
  'spell_protection_from_poison','spell_silence','spell_spiritual_weapon','spell_warding_bond',
  'spell_zone_of_truth',
  'spell_animate_dead','spell_aura_of_vitality','spell_beacon_of_hope','spell_bestow_curse',
  'spell_clairvoyance','spell_create_food_and_water','spell_daylight','spell_dispel_magic',
  'spell_feign_death','spell_glyph_of_warding','spell_magic_circle','spell_mass_healing_word',
  'spell_meld_into_stone','spell_protection_from_energy','spell_remove_curse','spell_revivify',
  'spell_sending','spell_speak_with_dead','spell_spirit_guardians','spell_tongues',
  'spell_water_walk','spell_wind_wall',
  'spell_aura_of_life','spell_aura_of_purity','spell_banishment','spell_control_water',
  'spell_death_ward','spell_divination','spell_freedom_of_movement','spell_guardian_of_faith',
  'spell_locate_creature','spell_stone_shape',
  'spell_commune','spell_contagion','spell_dispel_evil_and_good','spell_flame_strike',
  'spell_geas','spell_greater_restoration','spell_hallow','spell_insect_plague','spell_legend_lore',
  'spell_mass_cure_wounds','spell_planar_binding','spell_raise_dead','spell_scrying',
  'spell_summon_celestial',
  'spell_blade_barrier','spell_create_undead','spell_find_the_path','spell_forbiddance',
  'spell_harm','spell_heal','spell_heroes_feast','spell_planar_ally','spell_true_seeing',
  'spell_word_of_recall',
  'spell_conjure_celestial','spell_divine_word','spell_etherealness','spell_fire_storm',
  'spell_plane_shift','spell_power_word_fortify','spell_regenerate','spell_resurrection',
  'spell_symbol',
  'spell_antimagic_field','spell_control_weather','spell_earthquake','spell_holy_aura',
  'spell_astral_projection','spell_gate','spell_mass_heal','spell_power_word_heal',
  'spell_true_resurrection'
);

-- ─── Druid ────────────────────────────────────────────────────────────────────
UPDATE spells SET is_druid_spell = 1 WHERE id IN (
  'spell_druidcraft','spell_elementalism','spell_guidance','spell_mending','spell_poison_spray',
  'spell_produce_flame','spell_resistance','spell_shillelagh','spell_spare_the_dying',
  'spell_starry_wisp','spell_thorn_whip','spell_thunderclap',
  'spell_animal_friendship','spell_charm_person','spell_create_or_destroy_water','spell_cure_wounds',
  'spell_detect_magic','spell_detect_poison_and_disease','spell_entangle','spell_faerie_fire',
  'spell_fog_cloud','spell_goodberry','spell_healing_word','spell_ice_knife','spell_jump',
  'spell_longstrider','spell_protection_from_poison','spell_purify_food_and_drink',
  'spell_speak_with_animals','spell_thunderwave',
  'spell_animal_messenger','spell_barkskin','spell_beast_sense','spell_darkness','spell_darkvision',
  'spell_enhance_ability','spell_find_traps','spell_flame_blade','spell_flaming_sphere',
  'spell_gust_of_wind','spell_heat_metal','spell_hold_person','spell_lesser_restoration',
  'spell_locate_animals_or_plants','spell_locate_object','spell_moonbeam','spell_pass_without_trace',
  'spell_protection_from_poison','spell_spike_growth','spell_summon_beast',
  'spell_aura_of_vitality','spell_call_lightning','spell_conjure_animals','spell_daylight',
  'spell_dispel_magic','spell_feign_death','spell_meld_into_stone','spell_plant_growth',
  'spell_protection_from_energy','spell_revivify','spell_sleet_storm','spell_speak_with_plants',
  'spell_summon_fey','spell_water_breathing','spell_water_walk','spell_wind_wall',
  'spell_blight','spell_charm_monster','spell_confusion','spell_conjure_minor_elementals',
  'spell_conjure_woodland_beings','spell_control_water','spell_dominate_beast',
  'spell_freedom_of_movement','spell_giant_insect','spell_grasping_vine',
  'spell_hallucinatory_terrain','spell_ice_storm','spell_locate_creature','spell_stone_shape',
  'spell_stoneskin','spell_summon_elemental','spell_wall_of_fire',
  'spell_antilife_shell','spell_awaken','spell_commune_with_nature','spell_conjure_elemental',
  'spell_contagion','spell_geas','spell_greater_restoration','spell_insect_plague',
  'spell_mass_cure_wounds','spell_planar_binding','spell_reincarnate','spell_scrying',
  'spell_tree_stride','spell_wall_of_stone',
  'spell_conjure_fey','spell_find_the_path','spell_flesh_to_stone','spell_heal',
  'spell_heroes_feast','spell_move_earth','spell_planar_ally','spell_sunbeam',
  'spell_transport_via_plants','spell_wall_of_thorns','spell_wind_walk',
  'spell_fire_storm','spell_mirage_arcane','spell_plane_shift','spell_regenerate',
  'spell_reverse_gravity','spell_symbol',
  'spell_animal_shapes','spell_antipathy_sympathy','spell_control_weather','spell_earthquake',
  'spell_incendiary_cloud','spell_sunburst','spell_tsunami',
  'spell_foresight','spell_shapechange','spell_storm_of_vengeance','spell_true_resurrection'
);

-- ─── Bard ─────────────────────────────────────────────────────────────────────
UPDATE spells SET is_bard_spell = 1 WHERE id IN (
  'spell_blade_ward','spell_dancing_lights','spell_friends','spell_mage_hand',
  'spell_minor_illusion','spell_starry_wisp','spell_thunderclap','spell_true_strike',
  'spell_vicious_mockery',
  'spell_animal_friendship','spell_bane','spell_charm_person','spell_color_spray',
  'spell_command','spell_comprehend_languages','spell_cure_wounds','spell_detect_magic',
  'spell_disguise_self','spell_dissonant_whispers','spell_faerie_fire','spell_feather_fall',
  'spell_healing_word','spell_heroism','spell_identify','spell_illusory_script',
  'spell_longstrider','spell_silent_image','spell_sleep','spell_speak_with_animals',
  'spell_thunderwave','spell_unseen_servant',
  'spell_aid','spell_animal_messenger','spell_blindness_deafness','spell_calm_emotions',
  'spell_crown_of_madness','spell_detect_thoughts','spell_enhance_ability','spell_enthrall',
  'spell_find_traps','spell_heat_metal','spell_hold_person','spell_invisibility','spell_knock',
  'spell_lesser_restoration','spell_locate_animals_or_plants','spell_locate_object',
  'spell_magic_mouth','spell_mirror_image','spell_phantasmal_force','spell_see_invisibility',
  'spell_shatter','spell_silence','spell_suggestion','spell_zone_of_truth',
  'spell_bestow_curse','spell_clairvoyance','spell_dispel_magic','spell_fear',
  'spell_feign_death','spell_glyph_of_warding','spell_hypnotic_pattern','spell_leomunds_tiny_hut',
  'spell_major_image','spell_mass_healing_word','spell_nondetection','spell_plant_growth',
  'spell_sending','spell_speak_with_dead','spell_speak_with_plants','spell_stinking_cloud',
  'spell_tongues',
  'spell_charm_monster','spell_compulsion','spell_confusion','spell_dimension_door',
  'spell_freedom_of_movement','spell_greater_invisibility','spell_hallucinatory_terrain',
  'spell_locate_creature','spell_phantasmal_killer','spell_polymorph',
  'spell_animate_objects','spell_dominate_person','spell_dream','spell_geas',
  'spell_greater_restoration','spell_legend_lore','spell_mass_cure_wounds','spell_mislead',
  'spell_modify_memory','spell_planar_binding','spell_rarys_telepathic_bond','spell_scrying',
  'spell_seeming','spell_synaptic_static','spell_teleportation_circle',
  'spell_eyebite','spell_find_the_path','spell_guards_and_wards','spell_heroes_feast',
  'spell_ottos_irresistible_dance','spell_programmed_illusion','spell_true_seeing',
  'spell_etherealness','spell_mirage_arcane','spell_mordenkainens_magnificent_mansion',
  'spell_mordenkainens_sword','spell_power_word_fortify','spell_prismatic_spray',
  'spell_project_image','spell_regenerate','spell_resurrection','spell_symbol','spell_teleport',
  'spell_dominate_monster','spell_glibness','spell_mind_blank','spell_power_word_stun',
  'spell_foresight','spell_power_word_heal','spell_power_word_kill','spell_true_polymorph',
  'spell_weird'
);

-- ─── Paladin ──────────────────────────────────────────────────────────────────
UPDATE spells SET is_paladin_spell = 1 WHERE id IN (
  'spell_bless','spell_command','spell_compelled_duel','spell_cure_wounds',
  'spell_detect_evil_and_good','spell_detect_magic','spell_detect_poison_and_disease',
  'spell_divine_favor','spell_divine_smite','spell_heroism',
  'spell_protection_from_evil_and_good','spell_purify_food_and_drink',
  'spell_searing_smite','spell_shield_of_faith','spell_thunderous_smite','spell_wrathful_smite',
  'spell_aid','spell_find_steed','spell_gentle_repose','spell_lesser_restoration',
  'spell_locate_object','spell_magic_weapon','spell_prayer_of_healing',
  'spell_protection_from_poison','spell_shining_smite','spell_warding_bond','spell_zone_of_truth',
  'spell_aura_of_vitality','spell_blinding_smite','spell_create_food_and_water',
  'spell_crusaders_mantle','spell_daylight','spell_dispel_magic','spell_elemental_weapon',
  'spell_magic_circle','spell_remove_curse','spell_revivify','spell_spirit_guardians',
  'spell_aura_of_life','spell_aura_of_purity','spell_banishment','spell_death_ward',
  'spell_locate_creature','spell_staggering_smite',
  'spell_banishing_smite','spell_circle_of_power','spell_dispel_evil_and_good',
  'spell_geas','spell_raise_dead','spell_summon_celestial'
);

-- ─── Ranger ───────────────────────────────────────────────────────────────────
UPDATE spells SET is_ranger_spell = 1 WHERE id IN (
  'spell_alarm','spell_animal_friendship','spell_cure_wounds','spell_detect_magic',
  'spell_detect_poison_and_disease','spell_ensnaring_strike','spell_entangle','spell_fog_cloud',
  'spell_goodberry','spell_hail_of_thorns','spell_hunters_mark','spell_jump','spell_longstrider',
  'spell_speak_with_animals',
  'spell_animal_messenger','spell_barkskin','spell_beast_sense','spell_cordon_of_arrows',
  'spell_darkvision','spell_find_traps','spell_gust_of_wind','spell_lesser_restoration',
  'spell_locate_animals_or_plants','spell_locate_object','spell_pass_without_trace',
  'spell_protection_from_poison','spell_silence','spell_spike_growth','spell_summon_beast',
  'spell_conjure_animals','spell_conjure_barrage','spell_daylight','spell_lightning_arrow',
  'spell_nondetection','spell_plant_growth','spell_protection_from_energy','spell_revivify',
  'spell_speak_with_plants','spell_water_breathing','spell_water_walk','spell_wind_wall',
  'spell_conjure_woodland_beings','spell_freedom_of_movement','spell_grasping_vine',
  'spell_locate_creature','spell_stoneskin','spell_summon_elemental',
  'spell_commune_with_nature','spell_conjure_volley','spell_greater_restoration',
  'spell_steel_wind_strike','spell_summon_fey','spell_swift_quiver','spell_tree_stride'
);

-- ─── Sorcerer ─────────────────────────────────────────────────────────────────
UPDATE spells SET is_sorcerer_spell = 1 WHERE id IN (
  'spell_acid_splash','spell_blade_ward','spell_chill_touch','spell_dancing_lights',
  'spell_elementalism','spell_fire_bolt','spell_friends','spell_light','spell_mage_hand',
  'spell_mending','spell_message','spell_mind_sliver','spell_minor_illusion','spell_poison_spray',
  'spell_prestidigitation','spell_ray_of_frost','spell_shocking_grasp','spell_sorcerous_burst',
  'spell_thunderclap','spell_true_strike',
  'spell_burning_hands','spell_charm_person','spell_chromatic_orb','spell_color_spray',
  'spell_comprehend_languages','spell_detect_magic','spell_disguise_self',
  'spell_expeditious_retreat','spell_false_life','spell_feather_fall','spell_fog_cloud',
  'spell_grease','spell_ice_knife','spell_jump','spell_mage_armor','spell_magic_missile',
  'spell_ray_of_sickness','spell_shield','spell_silent_image','spell_sleep',
  'spell_thunderwave','spell_witch_bolt',
  'spell_alter_self','spell_arcane_vigor','spell_blindness_deafness','spell_blur',
  'spell_crown_of_madness','spell_darkness','spell_darkvision','spell_detect_thoughts',
  'spell_dragons_breath','spell_enhance_ability','spell_enlarge_reduce','spell_flaming_sphere',
  'spell_gust_of_wind','spell_hold_person','spell_invisibility','spell_knock','spell_levitate',
  'spell_mirror_image','spell_misty_step','spell_phantasmal_force','spell_scorching_ray',
  'spell_see_invisibility','spell_shatter','spell_spider_climb','spell_suggestion','spell_web',
  'spell_blink','spell_clairvoyance','spell_counterspell','spell_daylight','spell_dispel_magic',
  'spell_fear','spell_fireball','spell_fly','spell_gaseous_form','spell_haste',
  'spell_hypnotic_pattern','spell_lightning_bolt','spell_major_image',
  'spell_protection_from_energy','spell_sleet_storm','spell_slow','spell_stinking_cloud',
  'spell_tongues','spell_vampiric_touch','spell_water_breathing',
  'spell_banishment','spell_blight','spell_charm_monster','spell_confusion',
  'spell_dimension_door','spell_dominate_beast','spell_greater_invisibility','spell_ice_storm',
  'spell_polymorph','spell_stoneskin','spell_vitriolic_sphere','spell_wall_of_fire',
  'spell_animate_objects','spell_cloudkill','spell_cone_of_cold','spell_creation',
  'spell_dominate_person','spell_hold_monster','spell_insect_plague','spell_mislead',
  'spell_scrying','spell_seeming','spell_synaptic_static','spell_telekinesis',
  'spell_teleportation_circle','spell_wall_of_stone',
  'spell_arcane_gate','spell_chain_lightning','spell_circle_of_death','spell_disintegrate',
  'spell_eyebite','spell_globe_of_invulnerability','spell_move_earth',
  'spell_otilukes_freezing_sphere','spell_sunbeam','spell_true_seeing',
  'spell_delayed_blast_fireball','spell_etherealness','spell_finger_of_death','spell_fire_storm',
  'spell_plane_shift','spell_prismatic_spray','spell_reverse_gravity','spell_teleport',
  'spell_dominate_monster','spell_earthquake','spell_incendiary_cloud',
  'spell_power_word_stun','spell_sunburst',
  'spell_gate','spell_meteor_swarm','spell_power_word_kill','spell_time_stop','spell_wish'
);

-- ─── Warlock ──────────────────────────────────────────────────────────────────
UPDATE spells SET is_warlock_spell = 1 WHERE id IN (
  'spell_blade_ward','spell_chill_touch','spell_eldritch_blast','spell_friends',
  'spell_mage_hand','spell_mind_sliver','spell_minor_illusion','spell_poison_spray',
  'spell_prestidigitation','spell_thunderclap','spell_true_strike',
  'spell_armor_of_agathys','spell_arms_of_hadar','spell_charm_person',
  'spell_comprehend_languages','spell_detect_magic','spell_expeditious_retreat',
  'spell_hellish_rebuke','spell_hex','spell_illusory_script',
  'spell_protection_from_evil_and_good','spell_unseen_servant','spell_witch_bolt',
  'spell_cloud_of_daggers','spell_crown_of_madness','spell_darkness','spell_enthrall',
  'spell_hold_person','spell_invisibility','spell_mirror_image','spell_misty_step',
  'spell_ray_of_enfeeblement','spell_shatter','spell_spider_climb','spell_suggestion',
  'spell_counterspell','spell_dispel_magic','spell_fear','spell_fly','spell_gaseous_form',
  'spell_hunger_of_hadar','spell_hypnotic_pattern','spell_magic_circle','spell_major_image',
  'spell_remove_curse','spell_speak_with_dead','spell_summon_fey','spell_summon_undead',
  'spell_tongues','spell_vampiric_touch',
  'spell_banishment','spell_blight','spell_charm_monster','spell_dimension_door',
  'spell_hallucinatory_terrain','spell_phantasmal_killer','spell_summon_aberration',
  'spell_contact_other_plane','spell_dream','spell_hold_monster',
  'spell_jallarzis_storm_of_radiance','spell_mislead','spell_modify_memory',
  'spell_planar_binding','spell_scrying','spell_seeming','spell_synaptic_static',
  'spell_teleportation_circle',
  'spell_arcane_gate','spell_circle_of_death','spell_create_undead','spell_eyebite',
  'spell_flesh_to_stone','spell_mass_suggestion','spell_programmed_illusion',
  'spell_summon_fiend','spell_true_seeing',
  'spell_etherealness','spell_finger_of_death','spell_forcecage','spell_plane_shift',
  'spell_power_word_fortify','spell_symbol',
  'spell_demiplane','spell_dominate_monster','spell_befuddlement','spell_glibness',
  'spell_mind_blank','spell_power_word_stun',
  'spell_astral_projection','spell_gate','spell_imprisonment','spell_power_word_kill',
  'spell_true_polymorph','spell_weird','spell_wish'
);